version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: estoque-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: estoque_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: estoque-redis
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: estoque-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
